### ISSUE TITLE
Getting Google Maps API Registered and Setup

### ISSUE THREAD

**Issue by DrewBarlow** [Shah-Kush/TellMeAStory4#3]
As a user, I want to be able to see a map of the globe to better understand how other cultures experience life.

**Comment by jasonnach** [comment]
Test is located in test_maps.py

**Comment by jasonnach** [comment]
This establishes the map API and displays the map on the user page. It establishes a test to make sure that the map page is loaded. Due to constraints, we decided to use MapBox instead of Google Maps for our platform.

This also establishes a testing mechanism to add a story onto the map and to allow the server to send data points to the client via JSON format.
